### ISSUE TITLE
Score Range

### ISSUE THREAD

**Issue by dorofino** [arafattehsin/CognitiveRocket#1]
Hi Arafat, 
Thank for make it this NuGet so simple to implement, I'm new with ML.

I have a question in regards to the SentimentPrediction.score.

I was wondering if there is any way I set up a range for the score between 0 to 1
For example:
0.5 > positive
0.5 = neutral
0.5 < negative

I'm currently using Cognitive Service Text Analytics API, and as you probably know their score between 0-1 [Link](https://docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/how-tos/text-analytics-how-to-sentiment-analysis#step-3-view-results)

> The sentiment analyzer classifies text as predominantly positive or negative, assigning a score in the range of 0 to 1. Values close to 0.5 are neutral or indeterminate. A score of 0.5 indicates neutrality. When a string cannot be analyzed for sentiment or has no sentiment, the score is always 0.5 exactly. For example, if you pass in a Spanish string with an English language code, the score is 0.5.

Let me know if you know an easy way to implement this method.

Best Regards, 
Diego

**Comment by arafattehsin** [comment]
Hi Diego

Sure, let me look into that this weekend and I will get back to you. 

This sort of problem looks like more than classification i.e. (not true or false type) so let me dig into this first and then will update you.

Thanks
Arafat

**Comment by dorofino** [comment]
Excellent let me know If you need help testing it.

**Comment by arafattehsin** [comment]
Hi @dorofino - Apologies for getting back to you late. Just wanted to know if you looked at this approach? May be it would address your need. 

https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/BinaryClassification_SentimentAnalysis/SentimentAnalysis/SentimentAnalysisConsoleApp

**Comment by arafattehsin** [comment]
Closing this issue. Please feel free to ask in case you need any help with that.
